name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12]

    env:
      DJANGO_SETTINGS_MODULE: backend.settings.testing
      DEGUB: True
      SECRET_KEY: "django-insecure-j_03lk44+rxy9_vn$e0d52!@**8p@gj7sn*=5#)on!ntrko!(d"
      DATABASE_URL: psql://ga_user:ga_password@127.0.0.1:5432/ga_db

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: ga_user
          POSTGRES_PASSWORD: ga_password
          POSTGRES_DB: ga_db
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
#     - name: Install Dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements/ci-requirements.txt
#     - name: Run Tests
#       working-directory: ./src
#       run: |
#         python -m pytest
